package testcases.CWE690_NULL_Deref_From_Return;

import javax.servlet.http.*;

public class ServletMain extends HttpServlet {

	private static final long serialVersionUID = 1L; /* needed since Servlets are serializable */
	
	

	public void doPost(HttpServletRequest request, HttpServletResponse response) {
		doGet(request, response);
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) {
		doGetCWE1(request, response);
		doGetCWE2(request, response);
		doGetCWE3(request, response);
		doGetCWE4(request, response);
		doGetCWE5(request, response);
		doGetCWE6(request, response);
		doGetCWE7(request, response);
		doGetCWE8(request, response);
		doGetCWE9(request, response);
	}
	
	private static void doGetCWE1(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-1 */

			/* END-AUTOGENERATED-SERVLET-TESTS-1 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE1 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE2(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-2 */

			/* END-AUTOGENERATED-SERVLET-TESTS-2 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE2 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE3(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-3 */

			/* END-AUTOGENERATED-SERVLET-TESTS-3 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE3 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE4(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-4 */

			/* END-AUTOGENERATED-SERVLET-TESTS-4 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE4 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}
		
	private static void doGetCWE5(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-5 */

			/* END-AUTOGENERATED-SERVLET-TESTS-5 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE5 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {

				System.out.println("  " + ste.toString());
			} 
		}
	}		
		
	private static void doGetCWE6(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-6 */
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_01()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_02()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_03()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_04()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_05()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_06()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_07()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_08()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_09()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_10()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_11()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_12()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_13()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_14()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_15()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_16()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_17()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_21()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_22a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_31()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_41()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_42()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_45()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_51a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_52a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_53a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_54a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_61a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_66a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_67a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_68a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_71a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_72a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_73a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_74a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_75a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_equals_81a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_01()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_02()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_03()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_04()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_05()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_06()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_07()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_08()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_09()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_10()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_11()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_12()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_13()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_14()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_15()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_16()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_17()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_21()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_22a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_31()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_41()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_42()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_45()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_51a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_52a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_53a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_54a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_61a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_66a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_67a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_68a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_71a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_72a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_73a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_74a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_75a()).runTest(request, response);
			(new testcases.CWE690_NULL_Deref_From_Return.CWE690_NULL_Deref_From_Return__getParameter_Servlet_trim_81a()).runTest(request, response);
			/* END-AUTOGENERATED-SERVLET-TESTS-6 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE6 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}

	private static void doGetCWE7(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-7 */

			/* END-AUTOGENERATED-SERVLET-TESTS-7 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE7 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
	
	private static void doGetCWE8(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-8 */

			/* END-AUTOGENERATED-SERVLET-TESTS-8 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE8 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}	
	
	private static void doGetCWE9(HttpServletRequest request, HttpServletResponse response) {
		try {
			/* BEGIN-AUTOGENERATED-SERVLET-TESTS-9 */

			/* END-AUTOGENERATED-SERVLET-TESTS-9 */
		} catch (Throwable t) {

			/* this will only happen on an IOException or something (the runTest for the test cases will catch any exceptions from the test cases).  So, we just abort
			 * and write to the console (since we can't write to the response without possibly throwing another exception)
			 */
			
			System.out.println(
					" Caught thowable from doGetCWE9 ");

			System.out.println(" Throwable's message = " + t.getMessage());
			
			System.out.println("Stack trace below");

			StackTraceElement stes[] = t.getStackTrace();

			for (StackTraceElement ste : stes) {
				System.out.println("  " + ste.toString());
			} 
		}
	}		
}
